### ISSUE TITLE
Network Activation Issues

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/buddypress-activity-stream-hashtags#7]
Currently in bp-activity-hashtags-loader.php the plugin is set to Network: true on line 11. Because the plugin must be network activated, the Tag Cloud Widget offers up Activity Hashtags as an option within subsites in a multisite instance of WP. 

I'm not sure what the advantages of Network Activation are in this instance, could the Network: True line be omitted?

**Comment by r-a-y** [comment]
> could the Network: True line be omitted? 

Yeah, it could.

I think I added the `Network: true` because of the tag cloud widget.  I guess I could remove it with a check.  More to come.

**Comment by mrjarbenne** [comment]
Maybe I'm not thinking of a use-case. Were you thinking that subdomain admins may want to display the main domain hashtags in their sidebar? 

I can see the potential if hashtags were collated as a network-wide taxonomy, but currently hashtags can only be recorded from blog posts if they occur within the blog excerpt on the activity feed. (this is discussion for a separate ticket)

**Comment by r-a-y** [comment]
> Were you thinking that subdomain admins may want to display the main domain hashtags in their sidebar? 

Yeah, I think that was one of the main reasons.  But, as you pointed out, this probably caused the adminbar issue using the main Commons site reported the other day.

I think I'll probably just register the hashtags taxonomy only on the main BP site.

>  but currently hashtags can only be recorded from blog posts if they occur within the blog excerpt on the activity feed.

This was probably the main reason though, but I can do something better here.

**Comment by r-a-y** [comment]
@mrjarbenne - The latest commits only registers the hashtags taxonomy on the main BP site and removes the `'Network: true'`.

I have already added this to production.  You can network-deactivate the hashtags plugin now if you want.

**Comment by mrjarbenne** [comment]
Done. Thanks.
