### ISSUE TITLE
Issue with Comments button in activity stream

### ISSUE THREAD

**Issue by lalaloo070** [hwdsbcommons/buddypress-activity-stream-hashtags#8]
Uploaded plugin today for testing.  Works well.  When I click on a #hashtag I am directed to a link http://mysite.com/activity/tag/taggedword/ which is working.

Only problem is the Comment button disappears in the activity streams that appear on that page.

I can send you a link to view if you like.  Thanks
WP version : 4.5.3
Buddypress : 2.6.2

**Comment by mrjarbenne** [comment]
Have you tested this using one of the default themes (Twenty-xx). I'm not able to reproduce this issue. 

![2016-08-09_09-17-58](https://cloud.githubusercontent.com/assets/480667/17517706/9262d8ca-5e12-11e6-8113-d72588ac5319.png)
