### ISSUE TITLE
Ordering the widget results by $real_count

### ISSUE THREAD

**Issue by deikka** [hwdsbcommons/buddypress-activity-stream-hashtags#9]
Is there a way to order the widget results by the number of mentions? 

Thanks for the amazing work!

**Comment by r-a-y** [comment]
We piggyback off of the WordPress Tag Cloud widget to show activity hashtags.

Unfortunately, it doesn't look like the widget offers an option to change the sort order, however you can change the sort order of the tag cloud widget with code.

View this article for more info:
http://www.howtosolutions.net/2016/08/wordpress-changing-cloud-tag-widget-settings/
